version: "3.9"
services:
  mapimages:
    image: ghcr.io/afrith/ngimaps-mapimages
    build: ./mapimages
    volumes:
      - "./tiffs:/usr/share/nginx/html"

  tiler:
    image: ghcr.io/afrith/ngimaps-tiler
    build: ./tiler
    environment:
      - "FIFTYK_MOSAIC_URL=http://mapimages/50k/mosaic-internal.json"
    depends_on:
      - mapimages

  mapproxy:
    image: ghcr.io/afrith/ngimaps-mapproxy
    build: ./mapproxy
    volumes:
      - "./cache:/mapproxy/cache_data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - tiler

  seed:
    image: ghcr.io/afrith/ngimaps-mapproxy
    build: ./mapproxy
    volumes:
      - "./cache:/mapproxy/cache_data"
    depends_on:
      - tiler
      - mapproxy # Not strictly necessary, but ensures service is available for gateway service. Should use healthcheck instead.
    entrypoint: ""
    command: mapproxy-seed -f /mapproxy/mapproxy.yaml -s /mapproxy/seed.yaml --concurrency 4

  gateway:
    image: ghcr.io/afrith/ngimaps-gateway
    build: './gateway'
    ports:
      - "8080:80"
    volumes:
      - "./cache:/cache"
    depends_on:
      seed:
        condition: service_completed_successfully
      mapproxy:
        condition: service_healthy
