version: "3.9"
services:
  mapimages:
    build: ./mapimages
#    volumes:
#       - "/Users/grant/code/osm/za-25cm:/usr/share/nginx/html"

  tiler:
    build: ./tiler
    environment:
#      - "FIFTYK_MOSAIC_URL=https://grant.dev.openstreetmap.org/os-openmap-local-202210-cog-experiment/mosaic.json"
#      - "FIFTYK_MOSAIC_URL=http://mapimages/mosaic-internal.json"
       - "FIFTYK_MOSAIC_URL=https://grant.dev.openstreetmap.org/za-25cm/mosaic.json"
    depends_on:
      - mapimages

  mapproxy:
    build: ./mapproxy
    volumes:
      - "./cache:/mapproxy/cache_data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      - tiler

  seed:
    build: ./mapproxy
    volumes:
      - "./cache:/mapproxy/cache_data"
    depends_on:
      - tiler
      - mapproxy # Not strictly necessary, but ensures service is available for gateway service. Should use healthcheck instead.
    entrypoint: ""
    command: mapproxy-seed -f /mapproxy/mapproxy.yaml -s /mapproxy/seed.yaml --concurrency 4

  gateway:
    build: './gateway'
    ports:
      - "8080:80"
    volumes:
      - "./cache:/cache"
    depends_on:
#      seed:
#        condition: service_completed_successfully
      mapproxy:
        condition: service_healthy
